name: Hello World #workflows file to be recognised by github and to be executable

on:                            # Event  
   workflow_dispatch:             # Trigger 

jobs:
  print-hello-world:
    runs_on: ubuntu-latest


    steps:
    -name: Say Hello
    runs: echo "hello world"   
                     